Design: Add a transaction page
RIP-Comm/sossoldi pull request #31
Opened 2022-11-09 17:08 UTC by 0xbaggi

Done :
- Created CircularMenuItemWrap to add custom Text from CircularMenuItem
- Dynamic button
- Top Icon and Title

To-do:
- Set right icons

2022-11-09 22:30 UTC, FedericoBruzzone commented
Quick question.
Can you send us a screen of your work?

2022-11-09 22:33 UTC, FedericoBruzzone requested changes

2022-11-09 22:33 UTC, FedericoBruzzone commented on pubspec.lock
> -  equatable:
Why did you remove this?

2022-11-09 22:33 UTC, FedericoBruzzone commented on pubspec.lock
> -  fl_chart:
Why did you remove this?

2022-11-09 22:33 UTC, FedericoBruzzone commented on lib/pages/structure.dart
> +        //showSelectedLabels: false,
Remove this

2022-11-09 22:33 UTC, FedericoBruzzone commented on lib/pages/structure.dart
> +        //showUnselectedLabels: false,
Same above

2022-11-09 22:40 UTC, FedericoBruzzone requested changes

2022-11-09 22:40 UTC, FedericoBruzzone commented on lib/model/CircularMenuItemWrap.dart
> +class CircularMenuItemWrap extends CircularMenuItem {
You can find the `widget test file` in a folder `~./test/widget` (something like this). 
Please, can you add the test of this widget?

2022-11-10 13:51 UTC, 0xbaggi commented on pubspec.lock
> -  fl_chart:
It is an unused library.

2022-11-10 14:42 UTC, 0xbaggi commented
> 



> You wrote in you PR comment `Set right icons`. What it means? Should we open an issue about it?

I mean we have to choose the most appropriate icons on the page, for now I have only selected a few which I think will fit, but we can find better choices. I think we should open a issue when we have coded a first version of all the app because this task is needed for all pages.

2022-11-10 15:40 UTC, FedericoBruzzone commented
> 
 
You should be able to open the issue about it, right?
Thanks for making it known!

2022-11-10 15:41 UTC, FedericoBruzzone commented
> > Quick question. Can you send us a screen of your work?
> 
> ![Immagine 2022-11-10 153555](https://user-images.githubusercontent.com/39710037/201119668-3a7e4495-7965-4a66-9728-92a98989e3bf.png)
> 
> From Pixel XL (API 31).

Looks good!

2022-11-11 19:05 UTC, 0xbaggi commented
I have implemented the other changes in the last commit of this PR.

2022-11-13 09:33 UTC, FedericoBruzzone commented
Can I merge this PR?
@0xbaggi

2022-11-13 17:36 UTC, 0xbaggi commented
> After your opening the issue can I merge this PR? @0xbaggi

Yes! I just opened the issue ( #32 )

2022-11-16 07:49 UTC, merged