Design: Add settings page
RIP-Comm/sossoldi pull request #33
Opened 2022-11-18 19:46 UTC by 0xbaggi

Done:
- Settings page created, with a custom widget/class settings_card.
- Implemented the onTapped() function on cards but there are no linked pages yet.

![image](https://user-images.githubusercontent.com/39710037/202789577-1599cd32-dbe7-460d-881b-a5fbfff639f0.png)

2022-11-24 14:57 UTC, mikev-cw approved these changes

2022-11-25 06:34 UTC, FedericoBruzzone requested changes

2022-11-25 06:34 UTC, FedericoBruzzone commented on lib/custom_widgets/settings_card.dart
> +                          fontFamily: 'SF Pro Text',
I'd suggest you to use a macro for the font (and replace it where necessary, also in the other two widgets)

I apologize if you do not know what a macro is, I mean something like a global variable. 

**Let's talk about whether it is better to create a new file for the macros**

2022-11-25 06:34 UTC, FedericoBruzzone commented on lib/pages/settings_page.dart
> +                                    fontFamily: 'SF Pro Text'))
Same thing above

2022-11-25 06:34 UTC, FedericoBruzzone commented on lib/pages/settings_page.dart
> +                          fontFamily: 'SF Pro Text',
Same thing above

2022-11-25 06:42 UTC, FedericoBruzzone commented
Is the font size the same for all widgets?

2022-12-20 07:47 UTC, FedericoBruzzone commented
Need rebase :D

2022-12-25 20:24 UTC, closed without merging